"""index transactions(portfolio_id, date)

Revision ID: 87bc672d6b69
Revises: 29633dbf63f1
Create Date: 2026-09-08 20:50:13.829054

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87bc672d6b69'
down_revision: str | Sequence[str] | None = '29633dbf63f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_txn_portfolio_date', ['portfolio_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_portfolio_date')

    # ### end Alembic commands ###
